templates:
    obsidian: '%userprofile%\Documents\Notes\.obsidian\themes\pywal.css'
disabled:
    win-terminal: '%localappdata%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'
    alacritty: '~\alacritty\alacritty.totml'
wsl: []
wsl_enabled: false
light_mode: false