templates:
    obsidian: '%userprofile%\Documents\Notes\.obsidian\themes\pywal.css'
disabled:
    win-terminal: '%localappdata%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'
    alacritty: '~\alacritty\alacritty.totml'
# WSL distros for wpgtk theme application
# List format only:
#   No distros (none):         wsl: []
#   Single distro:             wsl: ['Ubuntu']
#   Multiple distros:          wsl: ['Ubuntu', 'Debian']
wsl: []
light_mode: false